### ISSUE TITLE
ArrayIndexOutOfBoundsException when AOT-compiling dotty

### ISSUE THREAD

**Issue by DarkDimius** [graalvm/graal#244]
https://gist.github.com/DarkDimius/7658a35cf31333533e35432f15bc5642

Classpath items to reproduce: http://d-d.me/svm-dotty-classpath.tar

**Comment by vjovanov** [comment]
Fixed in the upcoming 0.28 release.

**Comment by DarkDimius** [comment]
Thank you for fix, Vojin!

**Comment by vjovanov** [comment]
The new release is ready for [download](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html).
