### ISSUE TITLE
Existing method not found when AOT-compiling scalac 2.12.2

### ISSUE THREAD

**Issue by DarkDimius** [graalvm/graal#245]
https://gist.github.com/DarkDimius/584d7af6c5c51c573b175bb7bcbc4362

Jars needed to reproduce can be downloaded here: https://downloads.lightbend.com/scala/2.12.2/scala-2.12.2.tgz

**Comment by rcano** [comment]
Can we expect this to be fixed? no reaction whatsoever since report.

**Comment by vjovanov** [comment]
The issue is fixed already. It will be out with the next OTN release.

**Comment by vjovanov** [comment]
The new release is ready for [download](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html).
