### ISSUE TITLE
this reference escapes during construction in Loop.java

### ISSUE THREAD

**Issue by richardstartin** [graalvm/graal#257]
I just started browsing the source code and noticed [this reference escapes during construction](https://github.com/graalvm/graal/blob/45edd9103ebdeded3209a041a3103f21c1f45fcd/compiler/src/org.graalvm.compiler.core.common/src/org/graalvm/compiler/core/common/cfg/Loop.java#L44) - which can and will allow a partially constructed object to escape.

**Comment by gilles-duboscq** [comment]
I'll change it so that we fully build the `Loop` before adding it to its parent.

However, since we have pointers going both way there will always need to be some period of time where things will be inconsistant.

**Comment by richardstartin** [comment]
OK. It's a Java memory model problem, not one of consistency - you must not let references escape during the construction of the referent.

**Comment by gilles-duboscq** [comment]
OK. Will fix.
However please note that almost none of the compiler's data structures are made to be multi-thread safe!

**Comment by gilles-duboscq** [comment]
Should be fixed by fe84de0d188c7a12075c7b65606245843d6e7db8
