### ISSUE TITLE
NPE in TruffleInlining

### ISSUE THREAD

**Issue by arthurp** [graalvm/graal#259]
When running certain highly concurrent programs with dynamically generated DirectCallNodes, TruffleInlining can NPE on a null OptimizedCallTarget. [Stack trace](https://gist.github.com/arthurp/c7382b49cbb7613343b93a3a6e11dbb3). This was run on GraalVM 0.28.2.

I believe this is because TruffleInlining observes a partially constructed OptimizedDirectCallNode. This can happen because the TruffleInlining does not seem to lock the RootNode of the function containing the call node. This means that if that call node is created concurrently with the inliner running, it may be incomplete. I think this could be fixed by locking the RootNode when in getCallNodes during traversal. This would prevent the AST from changing while the call nodes are being extracted. The lock would not have held along with any other lock so it should be safe.

The code that constructs the DirectCallTarget is generated by the Truffle DSL and the generated code takes the RootNode lock as expected. I don't have a minimal test case of this, but I think I can build one if needed (though I am rather busy with paper writing, so it may take a while).

PS: I cannot actually think of a work around for this problem. So if anyone is aware of a way to get around this problem in the short term I would love to know about it.

**Comment by eregon** [comment]
Just a note, the code there seems to have changed to handle null for getRootNode():
https://github.com/graalvm/graal/blob/af260415d5c6e33ec126e08f2852d78d881709b2/compiler/src/org.graalvm.compiler.truffle/src/org/graalvm/compiler/truffle/TruffleInlining.java#L138
https://github.com/graalvm/graal/blob/af260415d5c6e33ec126e08f2852d78d881709b2/compiler/src/org.graalvm.compiler.truffle/src/org/graalvm/compiler/truffle/TruffleInlining.java#L192-L194

This is a change from @woess: 17d31a0c1dbb933915491307f9a728dcfddea4fa.

Re workaround, `-Dgraal.TruffleCompilerThreads=1` might help, as well as
`-Dgraal.TruffleBackgroundCompilation=false`.

**Comment by chumer** [comment]
That is interesting. This should not happen. Do you by chance call DirectCallNode before calling Node#insert on it? The parent pointer of nodes typically don't get reset to null. I assume that DirectCallNode#getRootNode() returns null.

**Comment by chumer** [comment]
Yeah. The change will be fixed in 0.29. That comes out this week.

**Comment by arthurp** [comment]
Ooops. I even tried to check if it was already fixed. I guess I failed. Sorry.

Thanks for the help. Looking forward to 0.29.
