### ISSUE TITLE
License confusion: GPL or GPL with classpath exception?

### ISSUE THREAD

**Issue by russpowers** [graalvm/graal#269]
Hi, I thought that this whole project was GPL with classpath exception based on the LICENSE.md files, but upon closer inspection I saw this text above the classpath exception:

```Certain source files distributed by Oracle America and/or its affiliates are subject to the following clarification and special exception to the GPL, but only where Oracle has expressly included in the particular source file's header the words "Oracle designates this particular file as subject to the "Classpath" exception as provided by Oracle in the LICENSE file that accompanied this code."```

After digging through some source files, it looks like everything under /truffle has the classpath exception stuff in the header, but everything under /compiler does not.  Is this intentional?  That makes the whole compiler effectively GPL.

Am I right in assuming that both the compiler and truffle are required to run?  That would make the whole project effectively GPL.  Unless the compiler is somehow packaged with the JVM?  Or maybe I am misunderstanding things.  Thanks in advance.

**Comment by russpowers** [comment]
I found some text answering this from an email exchange here: http://mail.openjdk.java.net/pipermail/graal-dev/2016-September/004541.html.

**Comment by eregon** [comment]
http://mail.openjdk.java.net/pipermail/graal-dev/2016-September/004545.html seems to more specifically address this.
Graal is not a dependency of Truffle, and Truffle languages generally do not depend on Graal directly.

I think we should clarify the licenses in the top-level README.
Truffle's README mentions it is licensed under the GPLv2 with classpath exception, but the Graal README does not mention the license.
Furthermore, https://github.com/graalvm/graal/blob/master/compiler/LICENSE.md is confusing since it mentions the `classpath exception` but it is applied to no files under `compiler/`.
Could we just remove that exception since it's not used in Graal?

**Comment by russpowers** [comment]
That's what I understood that thread to say, but today I looked at the JDK 9 instructions for TruffleRuby, and it requires adding `org.graalvm.graal_sdk.jar` and `jdk.internal.vm.compiler.jar` to the module path in order to run:

https://github.com/graalvm/truffleruby/blob/master/doc/user/using-java9.md

I was under the impression that the GPL'd compiler was separate and not a dependency of Truffle languages.  If the compiler is a dependency and is loaded by Truffle, the GPL of the compiler library would infect the whole codebase, right?  Would it be possible to have a Truffle language that doesn't have a dependency on the GPL'd compiler libraries?

**Comment by eregon** [comment]
The "Graal SDK" is not part of the compiler (the name is misleading).
Graal SDK is https://github.com/graalvm/graal/tree/master/sdk, which is under GPLv2 with the classpath exception. It is a dependency of Truffle, that is correct.

> I looked at the JDK 9 instructions for TruffleRuby, and it requires adding `org.graalvm.graal_sdk.jar` and `jdk.internal.vm.compiler.jar` to the module path in order to run.

The `jdk.internal.vm.compiler.jar` is not required, it's only if you want to run with Graal.
In other words,

```
$ export JAVACMD=...java 9...
$ bin/truffleruby -e 'p Truffle.graal?'
false
# Add -J-cmd to see the full command-line,
# showing only TruffleRuby, Truffle and the Graal SDK are on the classpath
```

runs fine and has no GPLv2 dependency.
Of course, without the Graal compiler the language implementation executes rather slowly.
But the important part is the Graal compiler is not a dependency of languages implementations.

**Comment by russpowers** [comment]
Ahh I see, that makes sense.  Thank you for the explanation.  It's too bad that Graal can't be included in any proprietary stuff, it's very exciting tech!  I agree with your suggestion above, it would be a very good idea to make this clear in a top-level README.

**Comment by eregon** [comment]
I updated the README in f109dcf4f7f7b9706bc7c4f5777db947610259ef.
Hopefully it is clearer now.
