### ISSUE TITLE
Major performance regression on AreWeFastYet Java benchmark set

### ISSUE THREAD

**Issue by smarr** [graalvm/graal#273]
The latest version of Graal core seems to have a major regression (50% longer runtimes for peak) on the [Are We Fast Yet benchmarks](http://github.com/smarr/are-we-fast-yet).

The issue might have been introduced somewhere after November 9th, and before or on Dec. 31st.
It does not seem to be in the GraalVM 0.30.2 release, which would narrow the timeframe further down to between Dec. 20th to Dec. 31st (if I can trust the date information on GitHub, and if there is no interaction between the core and enterprise features).

The benchmarks include small and very small benchmarks:
- Bounce
- CD
- DeltaBlue
- Havlak
- Json
- Mandelbrot
- Permute
- Queens
- Richards
- Towers

An overview of the results is available here: http://awfy-speed.stefan-marr.de/timeline/?exe=8%2C7%2C11%2C19&base=&ben=grid&env=1&revs=50&equid=on&quarts=on&extr=on

Graal C2 and GraalBasic are the same binary, using either C2 or Graal as top tier compiler.
GraalEnterprise is a GraalVM release, the last 2 data points both from GraalVM 0.30.2
Java8U66 is the host systems' java, currently 1.8.0_151.

Truffle performance does not seem to be affected.

**Comment by dougxc** [comment]
I wanted to look into the CD regression but hit this problem (with stock JDK):
```
dsimon@kruger-4 ~/g/a/b/Java> java -cp build Harness CD 5 5
Starting CD benchmark ...
Exception in thread "main" java.lang.NullPointerException
	at cd.RedBlackTree.treeInsert(Unknown Source)
	at cd.RedBlackTree.put(Unknown Source)
	at cd.CollisionDetector.lambda$handleNewFrame$0(Unknown Source)
	at som.Vector.forEach(Unknown Source)
	at cd.CollisionDetector.handleNewFrame(Unknown Source)
	at CD.benchmark(Unknown Source)
	at CD.innerBenchmarkLoop(Unknown Source)
	at Run.measure(Unknown Source)
	at Run.doRuns(Unknown Source)
	at Run.runBenchmark(Unknown Source)
	at Harness.main(Unknown Source)
dsimon@kruger-4 ~/g/a/b/Java> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by dougxc** [comment]
With https://github.com/graalvm/graal/commit/f109dcf4f7f7b9706bc7c4f5777db947610259ef, I don't see the regression on DeltaBlue.

C2:
```
> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
> java -cp ~/github/are-we-fast-yet/benchmarks/Java/build Harness DeltaBlue 3000 12000
...
DeltaBlue: iterations=3000 average: 18174us total: 54524798us
```

GraalCore:
```
> java -server -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -d64 -Djvmci.class.path.append=/Users/dsimon/PR273/graal/compiler/mxbuild/dists/graal.jar -Xbootclasspath/a:/Users/dsimon/PR273/graal/sdk/mxbuild/dists/graal-sdk.jar:/Users/dsimon/PR273/graal/truffle/mxbuild/dists/truffle-api.jar -XX:+UseJVMCICompiler -cp /Users/dsimon/github/are-we-fast-yet/benchmarks/Java/build Harness DeltaBlue 3000 12000
...
DeltaBlue: iterations=3000 average: 12952us total: 38858555us
```
That is, GraalCore is about 30% faster than C2. Is there something is the way I'm running the benchmark that would account for the difference with your results @smarr ?

**Comment by dougxc** [comment]
On Bounce, I also see no regression.

GraalCore:
```
> java -server -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -d64 -Djvmci.class.path.append=/Users/dsimon/PR273/graal/compiler/mxbuild/dists/graal.jar -Xbootclasspath/a:/Users/dsimon/PR273/graal/sdk/mxbuild/dists/graal-sdk.jar:/Users/dsimon/PR273/graal/truffle/mxbuild/dists/truffle-api.jar -XX:+UseJVMCICompiler -cp /Users/dsimon/github/are-we-fast-yet/benchmarks/Java/build Harness Bounce 3000 1500
...
Bounce: iterations=3000 average: 19817us total: 59453805us
```

C2:
```
> java -cp ~/github/are-we-fast-yet/benchmarks/Java/build Harness Bounce 3000 1500
...
Bounce: iterations=3000 average: 19796us total: 59388082us
```

**Comment by smarr** [comment]
Sorry for the noise. Turns out I didn't deploy graal-sdk.jar, which wasn't a problem for Truffle compilation in my case, but turned out to be relevant for normal Java compilation.

**Comment by eregon** [comment]
Should it not fail early if a jar is missing instead of reduced performance?

**Comment by smarr** [comment]
There were multiple class not found exceptions for `WordBase`, I think. I guess that meant the compiler threads just failed, and the program continued executing normally.

**Comment by dougxc** [comment]
You should have seen a bunch of exceptions on the benchmark console log.
This is one of the advantages of a Java based JIT compiler - exceptions in the compiler do not necessarily cause the VM to exit/crash. However, for benchmark executions you probably want more fail-fast behavior so I'd suggest adding the `-Dgraal.CompilationFailureAction=ExitVM` option.

**Comment by smarr** [comment]
Thanks, added the flag. Hopefully prevents similar issues in the future.
